name: Fine Art
favicon: null
layout_spectrum: 0.8042403606232256
typography_spectrum: 0.9447023458778858
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.7665977694559842
  lightness: 0.09492826531641185
  saturation: 0.7769330586306751
  rhythmicContrast: 0.9005724505987018
purpose: []
