favicon: null
name: Fine Art
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.6875
  brandStrength: 0
  rhythmicContrast: 0.5
  brandColors:
    - '#dbdbdb'
    - '#bfb8b0'
    - '#a99675'
    - '#36312e'
    - '#696973'
  lightness: 0.5625
typography_spectrum: 0.3261649
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.49785
analytics:
  twitter: null
  google: null
  facebook: null
