name: Fine Art
favicon: null
layout_spectrum: 0.8042403606232256
typography_spectrum: 0.9447023458778858
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dbdbdb'
    - '#bfb8b0'
    - '#a99675'
    - '#36312e'
    - '#696973'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
